In [10]:
import torch
import torch.nn as nn
import numpy as np
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [20]:
# 0) Prepare data
bc = datasets.load_breast_cancer() # sk learn dataset
X, y = bc.data, bc.target

n_samples, n_features = X.shape

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1234)

In [21]:
X.shape

(569, 30)

In [22]:
X_train[:5]

array([[1.288e+01, 1.822e+01, 8.445e+01, 4.931e+02, 1.218e-01, 1.661e-01,
        4.825e-02, 5.303e-02, 1.709e-01, 7.253e-02, 4.426e-01, 1.169e+00,
        3.176e+00, 3.437e+01, 5.273e-03, 2.329e-02, 1.405e-02, 1.244e-02,
        1.816e-02, 3.299e-03, 1.505e+01, 2.437e+01, 9.931e+01, 6.747e+02,
        1.456e-01, 2.961e-01, 1.246e-01, 1.096e-01, 2.582e-01, 8.893e-02],
       [1.113e+01, 2.244e+01, 7.149e+01, 3.784e+02, 9.566e-02, 8.194e-02,
        4.824e-02, 2.257e-02, 2.030e-01, 6.552e-02, 2.800e-01, 1.467e+00,
        1.994e+00, 1.785e+01, 3.495e-03, 3.051e-02, 3.445e-02, 1.024e-02,
        2.912e-02, 4.723e-03, 1.202e+01, 2.826e+01, 7.780e+01, 4.366e+02,
        1.087e-01, 1.782e-01, 1.564e-01, 6.413e-02, 3.169e-01, 8.032e-02],
       [1.263e+01, 2.076e+01, 8.215e+01, 4.804e+02, 9.933e-02, 1.209e-01,
        1.065e-01, 6.021e-02, 1.735e-01, 7.070e-02, 3.424e-01, 1.803e+00,
        2.711e+00, 2.048e+01, 1.291e-02, 4.042e-02, 5.101e-02, 2.295e-02,
        2.144e-02, 5.891e-03, 1.333e

In [23]:
y_train[:5]

array([1, 1, 1, 0, 1])

In [24]:
# scale
sc = StandardScaler()  # (x-mean)/std

# scale the features
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [25]:
X_test[:5]

array([[-7.08531507e-01,  1.53147488e-01, -7.01660159e-01,
        -6.88078077e-01,  3.64587320e-01, -1.87580513e-01,
        -5.95030234e-01, -7.07298817e-01,  1.63595638e-01,
         2.58015448e-01, -7.24126630e-01, -6.36267371e-01,
        -7.38634808e-01, -5.80654576e-01, -5.93452590e-01,
        -4.55933185e-01, -4.40879649e-01, -1.02140464e+00,
        -7.48964402e-01, -4.26671366e-01, -6.11874475e-01,
         4.73067624e-01, -6.12650158e-01, -5.87249315e-01,
         9.49334282e-01,  2.49984993e-01, -8.14051526e-03,
        -5.10720146e-01,  5.04338940e-01,  2.81120228e-01],
       [-9.57828382e-01, -2.24311189e+00, -9.69647197e-01,
        -8.56440421e-01, -3.86845333e-02, -8.98740381e-01,
        -8.03689538e-01, -8.26037067e-01, -1.60069331e+00,
         1.70721836e-01, -8.48839017e-01, -1.45566138e+00,
        -8.73222706e-01, -6.71546790e-01,  2.36300117e-01,
        -8.65989603e-01, -6.75568948e-01, -1.01412352e+00,
        -9.97146196e-01, -6.35268446e-01, -9.77081963e-

In [26]:


# convert to torch tensor

X_train = torch.from_numpy(X_train.astype(np.float32)) 
X_test = torch.from_numpy(X_test.astype(np.float32)) # 
y_train = torch.from_numpy(y_train.astype(np.float32))
y_test = torch.from_numpy(y_test.astype(np.float32))

In [27]:
X_train[:5]

tensor([[-0.3618, -0.2652, -0.3172, -0.4671,  1.8038,  1.1817, -0.5169,  0.1065,
         -0.3901,  1.3914,  0.1437, -0.1208,  0.1601, -0.1326, -0.5863, -0.1248,
         -0.5787,  0.1091, -0.2819, -0.1889, -0.2571, -0.2403, -0.2442, -0.3669,
          0.5449,  0.2481, -0.7109, -0.0797, -0.5280,  0.2506],
        [-0.8633,  0.7156, -0.8565, -0.7967, -0.0586, -0.4285, -0.5170, -0.6814,
          0.7948,  0.3882, -0.4545,  0.4009, -0.4357, -0.5216, -1.1631,  0.2724,
          0.0675, -0.2392,  1.1130,  0.3502, -0.8894,  0.3847, -0.8880, -0.7897,
         -1.0429, -0.4824, -0.5631, -0.7698,  0.4431, -0.2099],
        [-0.4334,  0.3251, -0.4129, -0.5036,  0.2029,  0.3169,  0.2114,  0.2923,
         -0.2941,  1.1295, -0.2249,  0.9890, -0.0743, -0.4596,  1.8909,  0.8176,
          0.5919,  1.7726,  0.1356,  0.7924, -0.6160, -0.0636, -0.5528, -0.6284,
         -0.1823, -0.1924, -0.2601, -0.0660, -1.1169,  0.0329],
        [-0.4191,  1.0410, -0.3904, -0.4502,  1.1198,  0.4183,  0.2901,  0.5127

In [28]:
y_train[:5]

tensor([1., 1., 1., 0., 1.])

In [29]:


# Create 2d tensors from 1 d tensor target [0,1,0,1,1,0,]

y_train = y_train.view(y_train.shape[0], 1)   # [[0], [1], [0], [1], [0]]
y_test = y_test.view(y_test.shape[0], 1)

In [31]:
y_train[:5]

tensor([[1.],
        [1.],
        [1.],
        [0.],
        [1.]])

In [2]:

# 1) Model
# Linear model f = wx + b , sigmoid at the end
class Model(nn.Module):
    def __init__(self, n_input_features):
        super(Model, self).__init__()
        self.linear = nn.Linear(n_input_features, 1) # output 1 

    def forward(self, x):
        y_pred = torch.sigmoid(self.linear(x))
        return y_pred

model = Model(n_features)

# 2) Loss and optimizer
num_epochs = 100
learning_rate = 0.01
criterion = nn.BCELoss()  # binary cross entropy loss 
# Formula:
# The BCE loss is calculated as:
# L(y, y') = -[y * log(y') + (1-y) * log(1-y')]
# where:
# y is the true label (0 or 1)
# y' is the predicted probability

optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# 3) Training loop
for epoch in range(num_epochs):
    # Forward pass and loss
    y_pred = model(X_train)
    loss = criterion(y_pred, y_train)

    # Backward pass and update
    loss.backward()  # dl_dw
    optimizer.step() # w -= lr * dl_dw

    # zero grad before new step
    optimizer.zero_grad() # grad = 0

    if (epoch+1) % 10 == 0:
        print(f'epoch: {epoch+1}, loss = {loss.item():.4f}')




epoch: 10, loss = 0.4941
epoch: 20, loss = 0.4276
epoch: 30, loss = 0.3808
epoch: 40, loss = 0.3459
epoch: 50, loss = 0.3189
epoch: 60, loss = 0.2972
epoch: 70, loss = 0.2793
epoch: 80, loss = 0.2643
epoch: 90, loss = 0.2515
epoch: 100, loss = 0.2403


In [5]:
X.shape

(569, 30)

In [6]:
y.shape

(569,)

In [8]:
X_test.shape

torch.Size([114, 30])

In [9]:
y_test.shape

torch.Size([114, 1])

In [33]:
with torch.no_grad(): # no grad tracking needed or detached mode
    y_predicted = model(X_test) # torch.Size([114, 1])
    print(y_predicted)  #  torch.Size([114, 1])  [[8.1594e-01],  probability valuees
        # [9.5226e-01],
        # [3.8130e-01],
        # [8.7944e-01],
        # [8.3211e-01],
        # [5.4134e-01],
        # [5.3138e-01],
    y_predicted_cls = y_predicted.round() # like sigmoid 0 or 1
    print(y_predicted_cls) # tensor([[1.], [0.], [1.], [0.], [1.], [0.], [1.], [0.], [1.], [0.]])
    print(y_predicted_cls.eq(y_test)) # tensor(6)
    print(y_predicted_cls.eq(y_test).sum()) # 103 correct predictions


    acc = y_predicted_cls.eq(y_test).sum() / float(y_test.shape[0])
    print(f'accuracy: {acc.item():.4f}')

tensor([[8.1594e-01],
        [9.5226e-01],
        [3.8130e-01],
        [8.7944e-01],
        [8.3211e-01],
        [5.4134e-01],
        [5.3138e-01],
        [9.4040e-01],
        [2.2605e-02],
        [5.5633e-02],
        [6.8985e-02],
        [7.6085e-01],
        [7.4036e-01],
        [6.1616e-01],
        [8.3795e-01],
        [1.2967e-03],
        [8.9966e-01],
        [9.3718e-01],
        [8.1520e-01],
        [2.0015e-01],
        [7.9463e-01],
        [2.3642e-01],
        [9.8438e-03],
        [2.7363e-03],
        [6.8561e-02],
        [7.9332e-01],
        [4.7861e-01],
        [8.5617e-01],
        [9.5465e-01],
        [9.2434e-01],
        [8.1005e-01],
        [8.9080e-01],
        [6.3612e-02],
        [7.3684e-01],
        [8.4748e-01],
        [5.9396e-01],
        [9.3603e-01],
        [3.4808e-01],
        [7.4059e-01],
        [8.9746e-01],
        [1.3999e-01],
        [8.7378e-01],
        [6.7185e-02],
        [7.3832e-01],
        [7.4758e-01],
        [8