In [1]:
import torch

In [2]:


print("Number of GPU: ", torch.cuda.device_count())
print("GPU Name: ", torch.cuda.get_device_name())


device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('Using device:', device)

Number of GPU:  1
GPU Name:  NVIDIA GeForce RTX 3050 6GB Laptop GPU
Using device: cuda


In [3]:
x = torch.empty(4,3,2)

In [4]:
x

tensor([[[5.7678e+17, 1.9282e-42],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00]]])

In [5]:
y = torch.zeros(2,3,4)

In [6]:
y

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
z = torch.ones(4,3,2)

In [8]:
z

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])

In [9]:
x.dtype

torch.float32

In [11]:
t = torch.ones(2,3, dtype=torch.float16)

In [12]:
t.type

<function Tensor.type>

In [13]:
t.dtype

torch.float16

In [15]:
t.size()

torch.Size([2, 3])

In [16]:
x = torch.randn(2,3)

In [17]:
x

tensor([[-0.3508,  1.2836, -0.8246],
        [-0.0998, -0.3552, -0.8478]])

In [18]:
y = torch.randn(2,3)

In [19]:
z = torch.add(x,y)

In [20]:
z

tensor([[-2.2186,  1.6987, -3.1384],
        [-0.8868, -0.6453, -0.7736]])